<?php
	session_start();
	include_once("../connection.php");
	$nam=$_POST['txtfname'];
	$lnam=$_POST['txtlname'];
	$uname=$_POST['txtun'];
	$email=$_POST['emailid'];
	$pass=$_POST['password'];
	$cpass=$_POST['conpassword'];
	$stat=$_POST['drpstate'];
	$chk=$_POST['rdbtype'];
	$city=$_POST['drpcity'];
	$phno=$_POST['txt_phno'];
	$gender=$_POST['rdb_gender'];
	if(isset($_POST['submit']))
	{
		if($nam==NULL)
		{
			$_SESSION['namerror']=1;
			header("location:signup.php");
		}
		else
		{
			$_SESSION['namevalue']=$nam;
		}
		if($phno==NULL)
		{
			$_SESSION['phnoerror']=1;
			header("location:signup.php");
		}
		else
		{
			$_SESSION['phnovalue']=$phno;
		}
		if($gender==NULL)
		{
			$_SESSION['gendererror']=1;
			header("location:signup.php");
		}
		if($lnam==NULL)
		{
			$_SESSION['lnamerror']=1;
			header("location:signup.php");
		}		
		else
		{
			$_SESSION['lnamevalue']=$lnam;
		}
		if($uname==NULL)
		{
			$_SESSION['unamerror']=1;
			header("location:signup.php");
		}
		else
		{
			$_SESSION['unamevalue']=$uname;
		}
			if($email==NULL)
		{
			$_SESSION['emailerror']=1;
			header("location:signup.php");
		}
		else
		{
			$_SESSION['emailvalue']=$email;
		}
			
			if($pass==NULL)
		{
			$_SESSION['passerror']=1;
			header("location:signup.php");
		}		
		if($cpass==NULL)
		{
			$_SESSION['cpasserror']=1;
			header("location:signup.php");
		}		
			if($city=="--select--")
		{
			$_SESSION['cityerror']=1;
			header("location:signup.php");
		}
		if($stat=="--select--")
		{
			$_SESSION['stateerror']=1;
			header("location:signup.php");
		}
		if($chk==null)
		{
			$_SESSION['typeerror']=1;
			header("location:signup.php");
		}
		if(!($pass==$cpass))
		{
			$_SESSION['comparepasserror']=1;
			header("location:signup.php");
		}
		echo $nam.$lnam.$uname.$email.$pass.$Stat.$city.$chk;
		if(!($nam==NULL || $lnam==NULL || $uname==NULL || $email==NULL || $pass==NULL || $stat=="--select--" || $city=="--select--" || $chk==NULL))
		{
			if($pass==$cpass)
			{	
				$result=mysql_query("select max(reg_id) as cid1 from signup_details");
				if($data=mysql_fetch_array($result))
				{
					$no = $data['cid1'];
					$no=$no+1;
				}
				else
				{
					$no=1;
				}
				echo $no.$nam.$lnam.$email.$phno.$gender.$chk.$no.$uname.$pass;
				$j=mysql_query("insert into signup_details values ('$no','$nam','$lnam','$email','$city','$phno','$gender','$chk')");
				$i=mysql_query("insert into login values ('$no','$uname','$pass')");
				if($j && $i)
				{
					if($chk=="member")
						header("location:memberdetails.php");
					if($chk=="traveller")
						header("location:travellerdetails.php");
				}
				else
				{
					//header("location:signup.php");
				}
			}
		}
	}
?>